version: '3'

services:
  springboot:
    build: 
      context: ../../
      dockerfile: infra/Docker/services/springboot+mysql_backend/Dockerfile
    container_name: springboot_mysql
    restart: unless-stopped
    volumes:
      - .:/volume
    ports:
      - "8001:8001"
    networks:
      - springboot-mysql
    depends_on:
      - mysqldb
      
  mysqldb:
    image: mysql:8
    networks:
      - springboot-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
networks:
  springboot-mysql:
    driver: bridge
