version: '3'

services:
  web:
    build: .
    command: java -jar /build/target/student-jdbc.jar
    volumes:
      - .:/volume
    ports:
      - "8001:8001"
    networks:
      - employee-mysql
    depends_on:
      - mysqldb
      
mysqldb:
    image: mysql:8
    networks:
      - student-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb  

networks:
  student-mysql: