version: '3'

services:
  springboot:
    build: 
      context: ../ ../
      dockerfole: infra/Docker/services/springboot+mysql_backend/Dockerfile
    container_name: springboot+mysql
    image: renilraphy33/springboot+mysql:1
    volumes:
      - appdata:/volume
    ports:
      - "8001:8001"
    networks:
      - student-mysql
    depends_on:
      - mysqldb
      
  mysqldb:
    image: mysql:8
    networks:
      - student-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
networks:
  student-mysql:
    driver: bridge